spring.application.name=sentinelcore-backend
server.port=8081
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/sentinelcore
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
